services:
  logging-db:
    image: mysql:latest
    volumes:
      - loggingdata:/var/lib/mysql
    env_file:
      - "shared.env"
  joke-db:
    image: mysql:latest
    volumes:
      - jokedata:/var/lib/mysql
    env_file:
      - "shared.env"
    ports:
      - 3306:3306
  user-db:
    image: mysql:latest
    volumes:
      - userdata:/var/lib/mysql
    env_file:
      - "shared.env"
  joke-service:
    build:
      context: .
      dockerfile: JokeService/Dockerfile
    depends_on:
      joke-db:
        condition: service_started
    ports:
      - 8080:8080
      
volumes:
  loggingdata:
  jokedata:
  userdata: