services:
  logging-db:
    image: mysql:latest
    volumes:
      - loggingdata:/var/lib/mysql
      - "./sql/savetheday.sql:/docker-entrypoint-initdb.d/1.sql"
    env_file:
      - "shared.env"
  tracing-db:
    image: mysql:latest
    volumes:
      - tracingdata:/var/lib/mysql
    env_file:
      - "shared.env"
  logger-service:
    build:
      context: .
      dockerfile: LoggerService/Dockerfile
    depends_on:
      logging-db:
        condition: service_started
    ports:
      - 8080
    deploy:
      replicas: 2
volumes:
  loggingdata:
  metricsdata:
  tracingdata:
  